apiVersion: v1
kind: Service
metadata:
  name: gromacs-portal-dev
spec:
  type: ClusterIP
  ports:
  - name: gromacs-portal-dev-port
    port: 80                                                                    
    targetPort: 9000    
  selector:
    app: gromacs-portal-dev

